/**
 * CAPABILITIES — the second authorization axis. THIS IS A COPY.
 *
 * SOURCE OF TRUTH: client-newsroom/src/lib/capabilities.ts.
 *
 * THE DISCIPLINE: do not edit this file alone. Change the source and mirror it
 * here in the same commit. A divergence between the two apps' idea of who holds
 * `add` is worse than either answer.
 *
 * NOT CLAIMED: that the two are byte-identical. The source's header used to
 * assert that about THIS file, and it was false for days — this file existed
 * only on an unmerged branch, so the path it named did not exist on main.
 * Nothing noticed, because nothing checks. The check that would make it a fact
 * is costed in the newsroom's issues/029: a scheduled cross-repo comparison,
 * waiting on a credential rather than on a design decision.
 *
 * The newsroom is the original because it owns the WRITE path: ACC360 has no
 * updateUserMetadata call anywhere and cannot grant or revoke anything. This
 * copy is read-only in practice.
 *
 * (Duplicated rather than shared as a package because these are two separate
 * repos on two separate Vercel projects with no workspace between them.
 * Publishing a package for ~40 lines of pure logic would add a release step to
 * every auth change. The mitigation is that both copies are pure, have no
 * imports, and are pinned by the same behaviour table in each repo's tests.)
 *
 * ── TIERS AND CAPABILITIES ARE ORTHOGONAL ────────────────────────────────
 *
 * `publicMetadata.role` answers "which tier is this person in" — none / hr /
 * exec / superexec / king. `publicMetadata.capabilities` answers "what extra
 * actions may they take". Neither implies the other:
 *
 *   role: "king"  capabilities: []          → clears every tier gate, CANNOT refresh
 *   role: null    capabilities: ["plus"]    → no tier access at all, MAY add entities
 *
 * There is deliberately NO "king implies everything" shortcut. A high tier
 * grants no capability implicitly, and nothing in this module or its callers
 * should ever add one. If a king needs `ultra`, a king is granted `ultra`.
 *
 * ── WHY NOT ZOD ──────────────────────────────────────────────────────────
 *
 * Both repos have zod, but on different majors (newsroom 3.x, ACC360 4.x).
 * Parsing that must behave identically in two places is the wrong thing to
 * route through two different versions of a library. The rules here are small
 * enough to hand-roll exactly, with no dependency to drift.
 */

/**
 * Every capability the system knows about. Additive — more come in later phases.
 *
 *   ultra   refresh the newsroom
 *   plus    Archive tracking
 *   add     add and delete entities in the newsroom
 *   crown   implies ultra, plus and add — see IMPLICATION below
 */
export const CAPABILITIES = ["ultra", "plus", "add", "crown"] as const;

/**
 * WHAT `crown` COVERS. An IMPLICATION, never an assignment.
 *
 * Granting crown means the stored array reads ["crown"] and nothing else.
 * hasCapability(meta, "add") is true because crown covers add, not because
 * "add" is in the array. Removing crown removes all of it in one edit.
 *
 * The failure this avoids: writing ultra, plus and add INTO the array
 * alongside crown. Revoking crown would then leave the other three behind —
 * someone keeps every privilege after the thing that granted them is taken
 * away, and the metadata gives no hint that anything is wrong.
 *
 * Expansion happens in hasCapability and NOWHERE ELSE. Specifically not in
 * parseCapabilities: that returns what is STORED, and a parser that invented
 * three entries nobody wrote would make "what does this user hold" disagree
 * with Clerk — the same half-revoked confusion arriving through the front door.
 * There is a test pinning parseCapabilities(["crown"]) to exactly ["crown"].
 */
const IMPLIES: Partial<Record<Capability, readonly Capability[]>> = {
  crown: ["ultra", "plus", "add"],
};

export type Capability = (typeof CAPABILITIES)[number];

/** Is this string one of the known capabilities? */
export function isCapability(value: unknown): value is Capability {
  return typeof value === "string" && (CAPABILITIES as readonly string[]).includes(value);
}

/**
 * Turns anything that might be `publicMetadata` into a validated capability set.
 *
 * Total by design — never throws, never rejects. Every malformed shape resolves
 * to an empty set, because the only safe reading of "I could not understand
 * this metadata" is "this person holds no capabilities":
 *
 *   { role: "exec" }                        → []   (key absent)
 *   { capabilities: undefined }             → []
 *   { capabilities: "ultra" }               → []   (string, not array)
 *   { capabilities: null }                  → []
 *   undefined / null / "nonsense" / 42      → []
 *   { capabilities: ["ultra", "plus"] }     → ["ultra", "plus"]
 *
 * UNKNOWN ENTRIES ARE IGNORED, NOT ERRORS. A capability this build has never
 * heard of is dropped and the rest are kept, so a metadata blob written by a
 * newer deploy does not lock a user out of the capabilities this deploy does
 * understand:
 *
 *   { capabilities: ["ultra", "telepathy"] } → ["ultra"]
 *
 * Duplicates collapse and order follows CAPABILITIES, so the result is stable
 * and comparable regardless of how the metadata happened to be written.
 */
export function parseCapabilities(metadata: unknown): Capability[] {
  if (typeof metadata !== "object" || metadata === null) return [];
  const raw = (metadata as { capabilities?: unknown }).capabilities;
  if (!Array.isArray(raw)) return [];
  return CAPABILITIES.filter((cap) => raw.includes(cap));
}

/**
 * Whether this metadata carries a given capability.
 *
 * Takes the raw metadata rather than a Clerk user object on purpose: the two
 * apps read it from different places — the newsroom off the session-token
 * claim (`sessionClaims.metadata`), ACC360 off the live user
 * (`currentUser().publicMetadata`) — and the newsroom uses BOTH, the claim for
 * deciding whether to render a control and a live read for authorizing the
 * mutation itself. One predicate serves all of them because it only cares
 * about the shape it is handed, not where that shape came from.
 */
export function hasCapability(metadata: unknown, capability: Capability): boolean {
  const held = parseCapabilities(metadata);
  if (held.includes(capability)) return true;
  // The only place implication is applied. See IMPLIES above for why it is not
  // applied in parseCapabilities.
  return held.some((c) => IMPLIES[c]?.includes(capability) ?? false);
}

/**
 * Everything this metadata grants, implications expanded — for DISPLAY, never
 * for a gate. A gate asks hasCapability about one capability; this answers
 * "what can this person do", which is a different question and one only a UI
 * asks.
 *
 * Kept separate from parseCapabilities on purpose. That one answers "what is
 * stored"; this one answers "what does it amount to". Conflating them is what
 * puts three capabilities nobody wrote into a page that claims to show Clerk.
 */
export function effectiveCapabilities(metadata: unknown): Capability[] {
  const held = parseCapabilities(metadata);
  const out = new Set<Capability>(held);
  for (const c of held) for (const implied of IMPLIES[c] ?? []) out.add(implied);
  return CAPABILITIES.filter((c) => out.has(c));
}
