/**
 * CAPABILITIES — the second authorization axis. THIS IS A COPY.
 *
 * SOURCE OF TRUTH: client-newsroom/src/lib/capabilities.ts. The logic below is
 * byte-identical to it on purpose. Do not edit this file alone — change the
 * source and mirror it here in the same commit. A divergence between the two
 * apps' idea of who holds `ultra` is worse than either answer.
 *
 * The newsroom is the original because it owns the WRITE path: ACC360 has no
 * updateUserMetadata call anywhere and cannot grant or revoke anything. This
 * copy is read-only in practice.
 *
 * (Duplicated rather than shared as a package because these are two separate
 * repos on two separate Vercel projects with no workspace between them.
 * Publishing a package for ~40 lines of pure logic would add a release step to
 * every auth change. The mitigation is that both copies are pure, have no
 * imports, and are pinned by the same behaviour table in each repo's tests.)
 *
 * ── TIERS AND CAPABILITIES ARE ORTHOGONAL ────────────────────────────────
 *
 * `publicMetadata.role` answers "which tier is this person in" — none / hr /
 * exec / superexec / king. `publicMetadata.capabilities` answers "what extra
 * actions may they take". Neither implies the other:
 *
 *   role: "king"  capabilities: []          → clears every tier gate, CANNOT refresh
 *   role: null    capabilities: ["plus"]    → no tier access at all, MAY add entities
 *
 * There is deliberately NO "king implies everything" shortcut. A high tier
 * grants no capability implicitly, and nothing in this module or its callers
 * should ever add one. If a king needs `ultra`, a king is granted `ultra`.
 *
 * ── WHY NOT ZOD ──────────────────────────────────────────────────────────
 *
 * Both repos have zod, but on different majors (newsroom 3.x, ACC360 4.x).
 * Parsing that must behave identically in two places is the wrong thing to
 * route through two different versions of a library. The rules here are small
 * enough to hand-roll exactly, with no dependency to drift.
 */

/** Every capability the system knows about. Additive — more come in later phases. */
export const CAPABILITIES = ["ultra", "plus"] as const;

export type Capability = (typeof CAPABILITIES)[number];

/** Is this string one of the known capabilities? */
export function isCapability(value: unknown): value is Capability {
  return typeof value === "string" && (CAPABILITIES as readonly string[]).includes(value);
}

/**
 * Turns anything that might be `publicMetadata` into a validated capability set.
 *
 * Total by design — never throws, never rejects. Every malformed shape resolves
 * to an empty set, because the only safe reading of "I could not understand
 * this metadata" is "this person holds no capabilities":
 *
 *   { role: "exec" }                        → []   (key absent)
 *   { capabilities: undefined }             → []
 *   { capabilities: "ultra" }               → []   (string, not array)
 *   { capabilities: null }                  → []
 *   undefined / null / "nonsense" / 42      → []
 *   { capabilities: ["ultra", "plus"] }     → ["ultra", "plus"]
 *
 * UNKNOWN ENTRIES ARE IGNORED, NOT ERRORS. A capability this build has never
 * heard of is dropped and the rest are kept, so a metadata blob written by a
 * newer deploy does not lock a user out of the capabilities this deploy does
 * understand:
 *
 *   { capabilities: ["ultra", "telepathy"] } → ["ultra"]
 *
 * Duplicates collapse and order follows CAPABILITIES, so the result is stable
 * and comparable regardless of how the metadata happened to be written.
 */
export function parseCapabilities(metadata: unknown): Capability[] {
  if (typeof metadata !== "object" || metadata === null) return [];
  const raw = (metadata as { capabilities?: unknown }).capabilities;
  if (!Array.isArray(raw)) return [];
  return CAPABILITIES.filter((cap) => raw.includes(cap));
}

/**
 * Whether this metadata carries a given capability.
 *
 * Takes the raw metadata rather than a Clerk user object on purpose: the two
 * apps read it from different places — this app off the live user
 * (`currentUser().publicMetadata`, and `useUser()` on the client), the newsroom
 * off the session-token claim. One predicate serves both because it only cares
 * about the shape it is handed, not where that shape came from.
 */
export function hasCapability(metadata: unknown, capability: Capability): boolean {
  return parseCapabilities(metadata).includes(capability);
}
